version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: subscribe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscribe
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscribe"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: subscribe-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085:8085" 
    environment:
      APP_ENV: "docker"

volumes:
  pgdata:
